<a href="https://colab.research.google.com/github/TRMaram/-_-/blob/main/Evaluation_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install cvss

Collecting cvss
  Downloading cvss-3.4-py2.py3-none-any.whl.metadata (3.8 kB)
Downloading cvss-3.4-py2.py3-none-any.whl (30 kB)
Installing collected packages: cvss
Successfully installed cvss-3.4

In [ ]:
!pip install openai

Requirement already satisfied: openai in /usr/local/lib/python3.11/dist-packages (1.93.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from openai) (4.9.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.10.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from openai) (2.11.7)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.11/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.11/dist-packages (from openai) (4.14.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (2025.6.15)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.1)

use this url to extract  multiple-choice questions (MCQs) based on Cyber Threat Intelligence (CTI) standards, threats, detection strategies, mitigation plans, and best practices. These questions are built using authoritative sources and standards within the CTI domain, including NIST, MITRE ATT&CK, and GDPR.
Format the response in a way that can easily be converted into a table in Python. : https://attack.mitre.org/techniques/T1548/001/

In [ ]:
!pip install google-generativeai

Requirement already satisfied: google-generativeai in /usr/local/lib/python3.11/dist-packages (0.8.5)
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (0.6.15)
Requirement already satisfied: google-api-core in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (2.25.1)
Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (2.174.0)
Requirement already satisfied: google-auth>=2.15.0 in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (2.38.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (5.29.5)
Requirement already satisfied: pydantic in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (2.11.7)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (4.67.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (4.14.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.11/dist-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.26.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core->google-generativeai) (1.70.0)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in /usr/local/lib/python3.11/dist-packages (from google-api-core->google-generativeai) (2.32.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth>=2.15.0->google-generativeai) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth>=2.15.0->google-generativeai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth>=2.15.0->google-generativeai) (4.9.1)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client->google-generativeai) (0.22.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client->google-generativeai) (0.2.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client->google-generativeai) (4.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic->google-generativeai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic->google-generativeai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic->google-generativeai) (0.4.1)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.73.1)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.71.2)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.11/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.2.3)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.6.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2025.6.15)

In [ ]:
import google.generativeai as genai
from google.colab import userdata
gemini_key = userdata.get('key') #api key in  the key logo in colab


genai.configure(api_key=gemini_key)

In [ ]:
# configuration du modèle
generation_config = {
  "temperature": 0,
  "top_p": 1,
}
# appel au modèle generative avec la configuration déjà fixée
model = genai.GenerativeModel(model_name= "gemini-2.5-flash-lite-preview-06-17",
                              generation_config = generation_config)

In [ ]:
prompt = """provide a well structured table that includes 50 varied multiple-choice questions (MCQs).
 extract THE multiple-choice questions (MCQs) based on Cyber Threat Intelligence (CTI) standards, threats, detection strategies, mitigation plans, and best practices. These questions are built using authoritative sources and standards within the CTI domain, including NIST, MITRE ATT&CK, and GDPR. Format the response in a way that can easily be converted into a table in Python.
Format the response in a way that can easily be converted into a table in Python  like this ([\n    {\n        \"question\": \"question ?\",\n        \"options\": {\n            \"a\": \"option a\",\n            \"b\": \"option b\",\n            \"c\": \"option c\",\n            \"d\": \"option d\"\n        },\n        \"answer\": \"d\"\n    }]). do not add any extra text to the response.
and avoid syntax errors """

on CWE

In [ ]:
prompt = """provide a well structured table that includes 50 varied multiple-choice questions (MCQs).
 extract THE multiple-choice questions (MCQs) based on Cyber Threat Intelligence (CTI) standards. Specifically on CWE. Format the response in a way that can easily be converted into a table in Python.
Format the response in a way that can easily be converted into a table in Python  like this ([\n    {\n        \"question\": \"question ?\",\n        \"options\": {\n            \"a\": \"option a\",\n            \"b\": \"option b\",\n            \"c\": \"option c\",\n            \"d\": \"option d\"\n        },\n        \"answer\": \"d\"\n    }]). do not add any extra text to the response.
and avoid syntax errors """

In [ ]:
model = genai.GenerativeModel(model_name= "gemini-2.5-flash-lite-preview-06-17",
                              generation_config = generation_config)
response = model.generate_content(prompt)
print(response)

response:
GenerateContentResponse(
    done=True,
    iterator=None,
    result=protos.GenerateContentResponse({
      "candidates": [
        {
          "content": {
            "parts": [
              {

In [ ]:
import re

def find_unescaped_quotes(text):
    # This regex matches double quotes that are not escaped
    unescaped_quotes = re.findall(r'(?<!\\)"', text)

    return unescaped_quotes
def escape_quotes(text):
    # Escape double quotes inside a string
    return text.replace('"', '\\"')

In [ ]:
import ast
import pandas as pd

# Accessing the content from the response object
# Adjust this based on the structure of your actual response object

try:


    # Extracting the text from the first candidate's content parts
    raw_text = response.candidates[0].content.parts[0].text


    cleaned_text = raw_text.replace("```python", "").replace("```", "").strip()
    escape_quotes(cleaned_text)
    # Safely evaluate the string to convert it into a Python object
    questions = ast.literal_eval(cleaned_text)

    # Convert the questions list to a pandas DataFrame
    df = pd.DataFrame(questions)

    # Display the DataFrame
    print(df)

except AttributeError as e:
    print(f"AttributeError: {e}")

except TypeError as e:
    print(f"TypeError: {e}")

                                             question  \
0   Which CWE category primarily deals with flaws ...
1   A vulnerability where an attacker can execute ...
2   Which CWE describes a situation where a progra...
3   A web application vulnerability that allows an...
4   Which CWE is associated with attackers manipul...
5   When a system fails to properly authenticate a...
6   A vulnerability that allows an attacker to acc...
7   Which CWE describes the execution of arbitrary...
8   When an attacker can trick a user's browser in...
9   Which CWE relates to the improper handling of ...
10  A vulnerability where an attacker can cause a ...
11  Which CWE involves the use of weak or predicta...
12  When sensitive information is exposed in error...
13  Which CWE describes the deserialization of unt...
14  A vulnerability where an attacker can bypass a...
15  Which CWE category deals with flaws in how acc...
16  When a program uses a hardcoded password or ot...
17  Which CWE is associated with the use of outdat...
18  A vulnerability where an attacker can inject m...
19  Which CWE describes the failure to properly sa...
20  When a system does not properly validate the o...
21  Which CWE is related to the improper handling ...
22  A vulnerability where an attacker can exploit ...
23  Which CWE describes the use of insecure or out...
24  When an attacker can manipulate the logic of a...
25  Which CWE is associated with the improper hand...
26  A vulnerability where an attacker can inject m...
27  Which CWE describes the failure to properly va...
28  When an attacker can exploit a flaw in how a p...
29  Which CWE is associated with the improper hand...
30  A vulnerability where an attacker can manipula...
31  Which CWE describes the improper validation of...
32  When an attacker can exploit a flaw in how a p...
33  Which CWE is associated with the failure to pr...
34  A vulnerability where an attacker can bypass s...
35  Which CWE describes the use of insecure or out...
36  When an attacker can inject malicious SQL stat...
37  Which CWE is associated with the improper hand...
38  A vulnerability where an attacker can cause a ...
39  Which CWE describes the failure to properly au...
40  When an attacker can trick a user's browser in...
41  Which CWE is associated with the improper hand...
42  A vulnerability where an attacker can execute ...
43  Which CWE describes the use of hardcoded passw...
44  When a system fails to properly validate the o...
45  Which CWE is associated with the improper hand...
46  A vulnerability where an attacker can access f...
47  Which CWE describes the deserialization of unt...
48  When an attacker can exploit a flaw in how a p...
49  Which CWE is associated with the improper hand...
50  A vulnerability where an attacker can inject m...
51  Which CWE describes the failure to properly va...

                                              options answer
0   {'a': 'CWE-700: Information Exposure', 'b': 'C...      b
1   {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      b
2   {'a': 'CWE-20: Improper Input Validation', 'b'...      a
3   {'a': 'SQL Injection (CWE-89)', 'b': 'Cross-Si...      b
4   {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      b
5   {'a': 'CWE-284: Improper Access Control', 'b':...      b
6   {'a': 'Cross-Site Scripting (XSS) (CWE-79)', '...      c
7   {'a': 'CWE-78: OS Command Injection', 'b': 'CW...      a
8   {'a': 'SQL Injection (CWE-89)', 'b': 'Cross-Si...      c
9   {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
10  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      b
11  {'a': 'CWE-310: Cryptographic Issues', 'b': 'C...      a
12  {'a': 'CWE-200: Information Exposure', 'b': 'C...      a
13  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      c
14  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
15  {'a': 'CWE-20: Improper Input Validation', 'b'...      b
16  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
17  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
18  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
19  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      c
20  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      c
21  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      c
22  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
23  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
24  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      c
25  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
26  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
27  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
28  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
29  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
30  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      a
31  {'a': 'CWE-20: Improper Input Validation', 'b'...      a
32  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
33  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
34  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
35  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
36  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      b
37  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
38  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      b
39  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      c
40  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
41  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
42  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
43  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
44  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
45  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
46  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      c
47  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
48  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
49  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      d
50  {'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...      a
51  {'a': 'CWE-20: Improper Input Validation', 'b'...      a

df_cleaned= pd.read_csv('/content/MCQs10.csv')
df_cleaned.head()

In [ ]:
df_cleaned= pd.DataFrame()
df_cleaned.head()

Empty DataFrame
Columns: []
Index: []

In [ ]:
df_cleaned = pd.concat([df_cleaned,df], ignore_index=True)
df_cleaned = df_cleaned.drop_duplicates(subset='question', keep='first')
df_cleaned

,question,options,answer
0,Which CWE category primarily deals with flaws ...,"{'a': 'CWE-700: Information Exposure', 'b': 'C...",b
1,A vulnerability where an attacker can execute ...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",b
2,Which CWE describes a situation where a progra...,"{'a': 'CWE-20: Improper Input Validation', 'b'...",a
3,A web application vulnerability that allows an...,"{'a': 'SQL Injection (CWE-89)', 'b': 'Cross-Si...",b
4,Which CWE is associated with attackers manipul...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",b
5,When a system fails to properly authenticate a...,"{'a': 'CWE-284: Improper Access Control', 'b':...",b
6,A vulnerability that allows an attacker to acc...,"{'a': 'Cross-Site Scripting (XSS) (CWE-79)', '...",c
7,Which CWE describes the execution of arbitrary...,"{'a': 'CWE-78: OS Command Injection', 'b': 'CW...",a
8,When an attacker can trick a user's browser in...,"{'a': 'SQL Injection (CWE-89)', 'b': 'Cross-Si...",c
9,Which CWE relates to the improper handling of ...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
10,A vulnerability where an attacker can cause a ...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",b
11,Which CWE involves the use of weak or predicta...,"{'a': 'CWE-310: Cryptographic Issues', 'b': 'C...",a
12,When sensitive information is exposed in error...,"{'a': 'CWE-200: Information Exposure', 'b': 'C...",a
13,Which CWE describes the deserialization of unt...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",c
14,A vulnerability where an attacker can bypass a...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
15,Which CWE category deals with flaws in how acc...,"{'a': 'CWE-20: Improper Input Validation', 'b'...",b
16,When a program uses a hardcoded password or ot...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
17,Which CWE is associated with the use of outdat...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
18,A vulnerability where an attacker can inject m...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
19,Which CWE describes the failure to properly sa...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",c
20,When a system does not properly validate the o...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",c
21,Which CWE is related to the improper handling ...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",c
22,A vulnerability where an attacker can exploit ...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
23,Which CWE describes the use of insecure or out...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
24,When an attacker can manipulate the logic of a...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",c
25,Which CWE is associated with the improper hand...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
26,A vulnerability where an attacker can inject m...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
27,Which CWE describes the failure to properly va...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
28,When an attacker can exploit a flaw in how a p...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
29,Which CWE is associated with the improper hand...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
30,A vulnerability where an attacker can manipula...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",a
31,Which CWE describes the improper validation of...,"{'a': 'CWE-20: Improper Input Validation', 'b'...",a
32,When an attacker can exploit a flaw in how a p...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
33,Which CWE is associated with the failure to pr...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
34,A vulnerability where an attacker can bypass s...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
35,Which CWE describes the use of insecure or out...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
36,When an attacker can inject malicious SQL stat...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",b
37,Which CWE is associated with the improper hand...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
38,A vulnerability where an attacker can cause a ...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",b
39,Which CWE describes the failure to properly au...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",c
41,Which CWE is associated with the improper hand...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
42,A vulnerability where an attacker can execute ...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
43,Which CWE describes the use of hardcoded passw...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
44,When a system fails to properly validate the o...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",d
46,A vulnerability where an attacker can access f...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",c
50,A vulnerability where an attacker can inject m...,"{'a': 'CWE-79: Cross-site Scripting (XSS)', 'b...",a
51,Which CWE describes the failure to properly va...,"{'a': 'CWE-20: Improper Input Validation', 'b'...",a

In [ ]:
df_cleaned.to_csv(r'MCQs_CWE.csv', index=False)

In [ ]:
from time import sleep
for i in range(1,11):

  prompt = """provide a well structured table that includes 50 varied multiple-choice questions (MCQs).
  extract THE multiple-choice questions (MCQs) based on Cyber Threat Intelligence (CTI) standards, threats, detection strategies, mitigation plans, and best practices. These questions are built using authoritative sources and standards within the CTI domain, including NIST, MITRE ATT&CK, and GDPR. Format the response in a way that can easily be converted into a table in Python.
  Format the response in a way that can easily be converted into a table in Python  like this ([\n    {\n        \"question\": \"question ?\",\n        \"options\": {\n            \"a\": \"option a\",\n            \"b\": \"option b\",\n            \"c\": \"option c\",\n            \"d\": \"option d\"\n        },\n        \"answer\": \"d\"\n    }]). do not add any extra text to the response.
  and avoid syntax errors """

  response = model.generate_content(prompt)
  print(response)

  import re

  def find_unescaped_quotes(text):
      # This regex matches double quotes that are not escaped
      unescaped_quotes = re.findall(r'(?<!\\)"', text)

      return unescaped_quotes
  def escape_quotes(text):
      # Escape double quotes inside a string
      return text.replace('"', '\\"')

  import ast
  import pandas as pd

  # Accessing the content from the response object
  # Adjust this based on the structure of your actual response object

  try:


      # Extracting the text from the first candidate's content parts
      raw_text = response.candidates[0].content.parts[0].text


      cleaned_text = raw_text.replace("```python", "").replace("```", "").strip()
      escape_quotes(cleaned_text)
      # Safely evaluate the string to convert it into a Python object
      questions = ast.literal_eval(cleaned_text)

      # Convert the questions list to a pandas DataFrame
      df = pd.DataFrame(questions)
  except AttributeError as e:
      print(f"AttributeError: {e}")

  except TypeError as e:
      print(f"TypeError: {e}")

  df_cleaned = pd.concat([df_cleaned,df], ignore_index=True)
  df_cleaned = df_cleaned.drop_duplicates(subset='question', keep='first')
  df_cleaned
  df_cleaned.to_csv(r'MCQs.csv', index=False)
  sleep(2)

ReadTimeout: HTTPConnectionPool(host='localhost', port=42841): Read timed out. (read timeout=600.0)

In [ ]:
df_cleaned

,question,options,answer,a,b,c,d
0,Which NIST publication provides guidance on es...,"{'a': 'NIST SP 800-53', 'b': 'NIST SP 800-171'...",d,NaN,NaN,NaN,NaN
1,What does the acronym STIX stand for in the co...,"{'a': 'Security Threat Information eXchange', ...",a,NaN,NaN,NaN,NaN
2,Which of the following is NOT a core objective...,"{'a': 'Improve incident response times', 'b': ...",c,NaN,NaN,NaN,NaN
3,The MITRE ATT&CK framework is primarily focuse...,{'a': 'Vulnerability scanning and remediation'...,b,NaN,NaN,NaN,NaN
4,Which of the following is an example of a CTI ...,"{'a': 'Amazon Web Services (AWS)', 'b': 'Micro...",c,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
1665,Which of the following is a benefit of continu...,{'a': 'Staying ahead of the evolving threat la...,a,NaN,NaN,NaN,NaN
1666,What is the purpose of a Cyber Threat Intellig...,{'a': 'To align CTI activities with organizati...,a,NaN,NaN,NaN,NaN
1667,Which of the following is a key element of a s...,{'a': 'Strong leadership support and a culture...,a,NaN,NaN,NaN,NaN
1669,Which of the following is a challenge in apply...,{'a': 'The diversity and heterogeneity of IoT ...,a,NaN,NaN,NaN,NaN
1670,What is the role of threat intelligence in ope...,{'a': 'To protect critical infrastructure and ...,a,NaN,NaN,NaN,NaN